apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-backup-script
data:
  backup_script.sh: |
    #!/bin/bash
    apt-get update
    apt-get install -y curl gpg ca-certificates postgresql-client
  
    curl -sL https://aka.ms/downloadazcopy-v10-linux | tar --strip-components=1 -xz -C /usr/local/bin
   
    echo "Taking PostgreSQL backup..."
    pg_dumpall -U $USER -h $HOST -p $PORT -v -f "/tmp/{{ .Values.file.filename }}$(date +'%Y-%m-%d')"
 
    echo "Compressing the backup file into a tarball..."
    tar -czf "/tmp/{{ .Values.file.filename }}$(date +'%Y-%m-%d').tar.gz" /tmp/{{ .Values.file.filename }}$(date +'%Y-%m-%d')

    echo "Storing PostgreSQL backup to Azure Blob Storage..."
    azcopy copy "/tmp/{{ .Values.file.filename }}$(date +'%Y-%m-%d').tar.gz" "$URL/backup-postgres/{{ .Values.folder.foldername }}/{{ .Values.file.filename }}$(date +'%Y-%m-%d')$AZURE_SAS_TOKEN"