apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-backup-script
data:
  backup_script.sh: |
    #!/bin/bash
    apt-get update
    apt-get install -y gnupg lsb-release curl

    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 656408E390CFB1F5
    echo "deb http://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
    apt-get update
    apt-get install -y mongodb-database-tools

  
    curl -sL https://aka.ms/downloadazcopy-v10-linux | tar --strip-components=1 -xz -C /usr/local/bin
   
    mongodump --host $HOST --port $PORT --authenticationDatabase=admin --username $USER --password $PGPASSWORD --archive="/tmp/{{ .Values.file.filename }}$(date +'%Y-%m-%d')"
  

    echo "Storing PostgreSQL backup to Azure Blob Storage..."
    azcopy copy "/tmp/{{ .Values.file.filename }}$(date +'%Y-%m-%d')" "$URL/backup-mongo/{{ .Values.folder.foldername }}/{{ .Values.file.filename }}$(date +'%Y-%m-%d')$AZURE_SAS_TOKEN"
