apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-mongo-config
data:
  POSTGRES_USER: "{{ .Values.postgres.user | default "myAdmin" }}"
  POSTGRES_HOST: "{{ include "mychart.host" . }}"
  POSTGRES_PORT: "{{ .Values.postgres.port | default "27017"}}"
  
  URL: "{{ .Values.postgres.url }}"
