apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: ubuntu
            command:
            - sh
            - -c
            - ./script.sh
            env:
            - name: AZURE_SAS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: sasToken
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRES_HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRES_PORT
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: URL
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRES_USER
           
            volumeMounts:
            - name: scripts
              mountPath: ./script.sh
              subPath: script.sh
          restartPolicy: OnFailure
          volumes:
          - name: scripts
            configMap:
              name: backup-script 
              items:
               - key: backup_script.sh
                 path: script.sh
                 mode: 0755