---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: 
  password: kNtI9Ad3jS  # base64 encoded password
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
stringData:
  sasToken: ?sp=racwdli&st=2024-01-02T06:05:43Z&se=2024-01-02T14:05:43Z&spr=https&sv=2022-11-02&sr=c&sig=2q4bu2YsoFyLSKDUKIXS2P9vqkAQ8HLNn8IPVvIFpBk%3D